# Generated by Django 5.1.3 on 2025-01-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_activetokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
