apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: expense-tracker
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - name: web-metrics
    port: {{ .Values.app.service.port }}
    targetPort: 8000
  selector:
    app: expense-tracker
