apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  CLIENT_SECRET: {{ .Values.app.secrets.clientSecret | quote }}
